_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 5
                - 53
                - 55
            "2":
                - 5
                - 53
                - 55
            "3":
                - 2
                - 16
                - 23
                - 24
                - 55
            "4": 3.8.20
            "5": 0.18.3
            "8":
                - 5
            "12": 0.18.3
            "13": linux-x86_64
activation:
    value: models.MLP.activations.tanh
activations:
    value: sigmoid
batch_size:
    value: 128
early_stopping:
    value: true
epochs:
    value: 100
hidden_layers:
    value:
        - 64
        - 32
learning_rate:
    value: 0.04648699988034417
loss_func:
    value: mse
model:
    value: regressor
optimizer:
    value: batch
