wandb_version: 1

activations:
  value: relu
batch_size:
  value: 32
early_stopping:
  value: true
epochs:
  value: 1000
hidden_layers:
  value:
  - 64
  - 32
learning_rate:
  value: 0.08647721491925174
loss_func:
  value: mse
model:
  value: regressor
optimizer:
  value: batch
