wandb_version: 1

activations:
  value: sigmoid
batch_size:
  value: 256
early_stopping:
  value: true
epochs:
  value: 1000
hidden_layers:
  value:
  - 32
  - 16
learning_rate:
  value: 0.052030627566982485
loss_func:
  value: mse
model:
  value: regressor
optimizer:
  value: batch
