wandb_version: 1

activations:
  value: sigmoid
batch_size:
  value: 64
early_stopping:
  value: true
epochs:
  value: 100
hidden_layers:
  value:
  - 64
  - 32
learning_rate:
  value: 0.061982170986472615
loss_func:
  value: mse
model:
  value: regressor
optimizer:
  value: batch
