wandb_version: 1

activations:
  value: relu
batch_size:
  value: 256
early_stopping:
  value: true
epochs:
  value: 500
hidden_layers:
  value:
  - 64
  - 32
learning_rate:
  value: 0.06410556442232197
loss_func:
  value: mse
model:
  value: regressor
optimizer:
  value: mini-batch
