wandb_version: 1

activations:
  value: sigmoid
batch_size:
  value: 128
early_stopping:
  value: true
epochs:
  value: 500
hidden_layers:
  value:
  - 128
  - 64
learning_rate:
  value: 0.03901678914628441
loss_func:
  value: mse
model:
  value: regressor
optimizer:
  value: sgd
