wandb_version: 1

activations:
  value: tanh
batch_size:
  value: 32
early_stopping:
  value: true
epochs:
  value: 100
hidden_layers:
  value:
  - 32
  - 16
learning_rate:
  value: 0.006606466823000806
loss_func:
  value: mse
model:
  value: regressor
optimizer:
  value: mini-batch
