wandb_version: 1

activations:
  value: sigmoid
batch_size:
  value: 64
early_stopping:
  value: true
epochs:
  value: 100
hidden_layers:
  value:
  - 32
  - 16
learning_rate:
  value: 0.06681200210440977
loss_func:
  value: mse
model:
  value: regressor
optimizer:
  value: sgd
