wandb_version: 1

activations:
  value: tanh
batch_size:
  value: 256
early_stopping:
  value: true
epochs:
  value: 1000
hidden_layers:
  value:
  - 64
  - 32
learning_rate:
  value: 0.0048989219160330754
loss_func:
  value: mse
model:
  value: regressor
optimizer:
  value: batch
