wandb_version: 1

activations:
  value: tanh
batch_size:
  value: 128
early_stopping:
  value: true
epochs:
  value: 1000
hidden_layers:
  value:
  - 128
  - 64
learning_rate:
  value: 0.07241889790131331
loss_func:
  value: mse
model:
  value: regressor
optimizer:
  value: mini-batch
