wandb_version: 1

activations:
  value: tanh
batch_size:
  value: 64
early_stopping:
  value: true
epochs:
  value: 500
hidden_layers:
  value:
  - 64
  - 32
learning_rate:
  value: 0.057253906784119554
loss_func:
  value: mse
model:
  value: regressor
optimizer:
  value: mini-batch
