wandb_version: 1

activations:
  value: tanh
batch_size:
  value: 32
early_stopping:
  value: true
epochs:
  value: 500
hidden_layers:
  value:
  - 128
  - 64
learning_rate:
  value: 0.06455515693069058
loss_func:
  value: mse
model:
  value: regressor
optimizer:
  value: mini-batch
