wandb_version: 1

activations:
  value: relu
batch_size:
  value: 256
early_stopping:
  value: true
epochs:
  value: 1000
hidden_layers:
  value:
  - 128
  - 64
learning_rate:
  value: 0.07049091991710602
loss_func:
  value: mse
model:
  value: regressor
optimizer:
  value: sgd
