wandb_version: 1

activations:
  value: tanh
batch_size:
  value: 256
early_stopping:
  value: true
epochs:
  value: 500
hidden_layers:
  value:
  - 64
  - 32
learning_rate:
  value: 0.06370710926415082
loss_func:
  value: mse
model:
  value: regressor
optimizer:
  value: sgd
