wandb_version: 1

activations:
  value: relu
batch_size:
  value: 32
early_stopping:
  value: true
epochs:
  value: 100
hidden_layers:
  value:
  - 128
  - 64
learning_rate:
  value: 0.03373826464499575
loss_func:
  value: mse
model:
  value: regressor
optimizer:
  value: sgd
