wandb_version: 1

activations:
  value: relu
batch_size:
  value: 256
early_stopping:
  value: true
epochs:
  value: 500
hidden_layers:
  value:
  - 128
  - 64
learning_rate:
  value: 0.08019968714481822
loss_func:
  value: mse
model:
  value: regressor
optimizer:
  value: sgd
