wandb_version: 1

activations:
  value: sigmoid
batch_size:
  value: 32
early_stopping:
  value: true
epochs:
  value: 500
hidden_layers:
  value:
  - 64
  - 32
learning_rate:
  value: 0.06441605557580889
loss_func:
  value: mse
model:
  value: regressor
optimizer:
  value: batch
