wandb_version: 1

activations:
  value: relu
batch_size:
  value: 32
early_stopping:
  value: true
epochs:
  value: 1000
hidden_layers:
  value:
  - 128
  - 64
learning_rate:
  value: 0.055449881094529106
loss_func:
  value: mse
model:
  value: regressor
optimizer:
  value: mini-batch
