wandb_version: 1

activations:
  value: tanh
batch_size:
  value: 256
early_stopping:
  value: true
epochs:
  value: 500
hidden_layers:
  value:
  - 32
  - 16
learning_rate:
  value: 0.0009006597857988745
loss_func:
  value: mse
model:
  value: regressor
optimizer:
  value: batch
