wandb_version: 1

activations:
  value: tanh
batch_size:
  value: 256
early_stopping:
  value: true
epochs:
  value: 100
hidden_layers:
  value:
  - 128
  - 64
learning_rate:
  value: 0.033591432409512796
loss_func:
  value: cce
model:
  value: classifier
optimizer:
  value: mini-batch
