wandb_version: 1

activations:
  value: tanh
batch_size:
  value: 128
early_stopping:
  value: true
epochs:
  value: 500
hidden_layers:
  value:
  - 128
  - 64
learning_rate:
  value: 0.03633198747869298
loss_func:
  value: cce
model:
  value: classifier
optimizer:
  value: batch
