wandb_version: 1

activations:
  value: sigmoid
batch_size:
  value: 32
early_stopping:
  value: true
epochs:
  value: 500
hidden_layers:
  value:
  - 32
  - 16
learning_rate:
  value: 0.049247802842329415
loss_func:
  value: cce
model:
  value: classifier
optimizer:
  value: sgd
