wandb_version: 1

activations:
  value: tanh
batch_size:
  value: 64
early_stopping:
  value: true
epochs:
  value: 500
hidden_layers:
  value:
  - 128
  - 64
learning_rate:
  value: 0.013214797812394177
loss_func:
  value: cce
model:
  value: classifier
optimizer:
  value: mini-batch
