wandb_version: 1

activations:
  value: sigmoid
batch_size:
  value: 32
early_stopping:
  value: true
epochs:
  value: 100
hidden_layers:
  value:
  - 32
  - 16
learning_rate:
  value: 0.02654942328484105
loss_func:
  value: cce
model:
  value: classifier
optimizer:
  value: sgd
