wandb_version: 1

activations:
  value: relu
batch_size:
  value: 256
early_stopping:
  value: true
epochs:
  value: 100
hidden_layers:
  value:
  - 64
  - 32
learning_rate:
  value: 0.047523889508996976
loss_func:
  value: cce
model:
  value: classifier
optimizer:
  value: sgd
