wandb_version: 1

activations:
  value: sigmoid
batch_size:
  value: 256
early_stopping:
  value: true
epochs:
  value: 1000
hidden_layers:
  value:
  - 64
  - 32
learning_rate:
  value: 0.030710830090849617
loss_func:
  value: cce
model:
  value: classifier
optimizer:
  value: batch
