wandb_version: 1

activations:
  value: tanh
batch_size:
  value: 256
early_stopping:
  value: true
epochs:
  value: 100
hidden_layers:
  value:
  - 32
  - 16
learning_rate:
  value: 0.04299327194674153
loss_func:
  value: cce
model:
  value: classifier
optimizer:
  value: sgd
