wandb_version: 1

activations:
  value: relu
batch_size:
  value: 128
early_stopping:
  value: true
epochs:
  value: 1000
hidden_layers:
  value:
  - 32
  - 16
learning_rate:
  value: 0.00651709302375796
loss_func:
  value: cce
model:
  value: classifier
optimizer:
  value: sgd
