wandb_version: 1

activations:
  value: sigmoid
batch_size:
  value: 128
early_stopping:
  value: true
epochs:
  value: 100
hidden_layers:
  value:
  - 64
  - 32
learning_rate:
  value: 0.009468458164346437
loss_func:
  value: cce
model:
  value: classifier
optimizer:
  value: mini-batch
