wandb_version: 1

activations:
  value: relu
batch_size:
  value: 64
early_stopping:
  value: true
epochs:
  value: 500
hidden_layers:
  value:
  - 128
  - 64
learning_rate:
  value: 0.02452722997916416
loss_func:
  value: cce
model:
  value: classifier
optimizer:
  value: batch
