wandb_version: 1

activations:
  value: relu
batch_size:
  value: 256
early_stopping:
  value: true
epochs:
  value: 1000
hidden_layers:
  value:
  - 128
  - 64
learning_rate:
  value: 0.008992591653889196
loss_func:
  value: cce
model:
  value: classifier
optimizer:
  value: mini-batch
