wandb_version: 1

activations:
  value: relu
batch_size:
  value: 256
early_stopping:
  value: true
epochs:
  value: 500
hidden_layers:
  value:
  - 32
  - 16
learning_rate:
  value: 0.042541776822621585
loss_func:
  value: cce
model:
  value: classifier
optimizer:
  value: mini-batch
