_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 5
                - 53
                - 55
            "2":
                - 5
                - 53
                - 55
            "3":
                - 2
                - 16
                - 23
                - 24
                - 55
            "4": 3.8.20
            "5": 0.18.3
            "8":
                - 5
            "12": 0.18.3
            "13": linux-x86_64
activation:
    value: models.MLP.activations.tanh
activations:
    value: tanh
batch_size:
    value: 64
early_stopping:
    value: true
epochs:
    value: 500
hidden_layers:
    value:
        - 128
        - 64
learning_rate:
    value: 0.009437897324407307
loss_func:
    value: bce
model:
    value: multi-label
optimizer:
    value: batch
