wandb_version: 1

activations:
  value: sigmoid
batch_size:
  value: 256
early_stopping:
  value: true
epochs:
  value: 100
hidden_layers:
  value:
  - 128
  - 64
learning_rate:
  value: 0.03781995990169515
loss_func:
  value: bce
model:
  value: multi-label
optimizer:
  value: mini-batch
