wandb_version: 1

activations:
  value: sigmoid
batch_size:
  value: 64
early_stopping:
  value: true
epochs:
  value: 500
hidden_layers:
  value:
  - 128
  - 64
learning_rate:
  value: 0.02424234190676081
loss_func:
  value: bce
model:
  value: multi-label
optimizer:
  value: batch
