wandb_version: 1

activations:
  value: relu
batch_size:
  value: 128
early_stopping:
  value: true
epochs:
  value: 500
hidden_layers:
  value:
  - 32
  - 16
learning_rate:
  value: 0.064158014919822
loss_func:
  value: bce
model:
  value: multi-label
optimizer:
  value: mini-batch
