wandb_version: 1

activations:
  value: relu
batch_size:
  value: 64
early_stopping:
  value: true
epochs:
  value: 100
hidden_layers:
  value:
  - 128
  - 64
learning_rate:
  value: 0.01693724707864895
loss_func:
  value: bce
model:
  value: multi-label
optimizer:
  value: batch
