wandb_version: 1

activations:
  value: relu
batch_size:
  value: 128
early_stopping:
  value: true
epochs:
  value: 1000
hidden_layers:
  value:
  - 64
  - 32
learning_rate:
  value: 0.001303687665369656
loss_func:
  value: bce
model:
  value: multi-label
optimizer:
  value: sgd
