wandb_version: 1

activations:
  value: tanh
batch_size:
  value: 128
early_stopping:
  value: true
epochs:
  value: 1000
hidden_layers:
  value:
  - 128
  - 64
learning_rate:
  value: 0.003636623985879258
loss_func:
  value: bce
model:
  value: multi-label
optimizer:
  value: sgd
