wandb_version: 1

activations:
  value: sigmoid
batch_size:
  value: 64
early_stopping:
  value: true
epochs:
  value: 1000
hidden_layers:
  value:
  - 64
  - 32
learning_rate:
  value: 0.027643370399240745
loss_func:
  value: bce
model:
  value: multi-label
optimizer:
  value: batch
