wandb_version: 1

activations:
  value: sigmoid
batch_size:
  value: 32
early_stopping:
  value: true
epochs:
  value: 1000
hidden_layers:
  value:
  - 128
  - 64
learning_rate:
  value: 0.003021536353567076
loss_func:
  value: bce
model:
  value: multi-label
optimizer:
  value: batch
