wandb_version: 1

activations:
  value: relu
batch_size:
  value: 128
early_stopping:
  value: true
epochs:
  value: 100
hidden_layers:
  value:
  - 64
  - 32
learning_rate:
  value: 0.04931198262103527
loss_func:
  value: bce
model:
  value: multi-label
optimizer:
  value: batch
