wandb_version: 1

activations:
  value: relu
batch_size:
  value: 256
early_stopping:
  value: true
epochs:
  value: 100
hidden_layers:
  value:
  - 64
  - 32
learning_rate:
  value: 0.09721868066264414
loss_func:
  value: bce
model:
  value: multi-label
optimizer:
  value: batch
