wandb_version: 1

activations:
  value: tanh
batch_size:
  value: 32
early_stopping:
  value: true
epochs:
  value: 500
hidden_layers:
  value:
  - 32
  - 16
learning_rate:
  value: 0.005433089398351272
loss_func:
  value: bce
model:
  value: multi-label
optimizer:
  value: batch
