wandb_version: 1

activations:
  value: sigmoid
batch_size:
  value: 256
early_stopping:
  value: true
epochs:
  value: 100
hidden_layers:
  value:
  - 64
  - 32
learning_rate:
  value: 0.09534942148105356
loss_func:
  value: bce
model:
  value: multi-label
optimizer:
  value: batch
