wandb_version: 1

activations:
  value: tanh
batch_size:
  value: 128
early_stopping:
  value: true
epochs:
  value: 500
hidden_layers:
  value:
  - 64
  - 32
learning_rate:
  value: 0.05906552707168491
loss_func:
  value: bce
model:
  value: multi-label
optimizer:
  value: batch
