wandb_version: 1

activations:
  value: tanh
batch_size:
  value: 32
early_stopping:
  value: true
epochs:
  value: 100
hidden_layers:
  value:
  - 64
  - 32
learning_rate:
  value: 0.051625511378475125
loss_func:
  value: bce
model:
  value: multi-label
optimizer:
  value: batch
