wandb_version: 1

activations:
  value: relu
batch_size:
  value: 256
early_stopping:
  value: true
epochs:
  value: 100
hidden_layers:
  value:
  - 32
  - 16
learning_rate:
  value: 0.08869005472836812
loss_func:
  value: bce
model:
  value: multi-label
optimizer:
  value: sgd
