_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 5
                - 53
                - 55
            "2":
                - 5
                - 53
                - 55
            "3":
                - 2
                - 23
                - 55
            "4": 3.8.20
            "5": 0.18.3
            "8":
                - 5
            "12": 0.18.3
            "13": linux-x86_64
activation:
    value: models.MLP.activations.sigmoid
batch_size:
    value: 64
epochs:
    value: 1000
hidden_layers:
    value:
        - 64
        - 32
learning_rate:
    value: 0.001
optimizer:
    value: sgd
